### ISSUE TITLE
Ffi issues

### ISSUE THREAD

**Issue by joneshf** [Jonplussed/purescript-number-format#2]
These modules are unsafe from a compilation standpoint. For more info see here: https://github.com/purescript/purescript/wiki/FFI-tips#avoid-calling-ps-code-from-within-js-directly

Culprits are lines like: https://github.com/Jonplussed/purescript-number-format/blob/master/src/Number/Format/Maybe.purs#L14

Should be as simple as taking the `Just`/`Nothing` functions into the ffi and using them there.

**Comment by Jonplussed** [comment]
@joneshf I hadn't seen the PureScript wiki before; thanks for the link and the heads-up re: FFI! I made use of a couple of the techniques listed in the wiki to simplify the functions and remove the FFI problems. You can see the changes in PR #4.

**Comment by joneshf** [comment]
Jawesome!
