### ISSUE TITLE
Safe versions

### ISSUE THREAD

**Issue by joneshf** [Jonplussed/purescript-number-format#3]
Re #1
What are your thoughts for providing some safe versions that aren't wrapped in a `Maybe` or in an `Eff`? Only for the more common choices. Stuff like `toBinString :: Number -> String` or `toHexString :: Number -> String` would be pretty nice to have.

Pretty easy to implement as well:

``` purescript
toBinString :: Number -> String
toBinString = fromJust <<< toString "2"

toHexString :: Number -> String
toHexString = fromJust <<< toString "16"
```

**Comment by Jonplussed** [comment]
@joneshf That sounds great. Any other formatting functions you think should be included by default (like `toUSDString` to give a precision of 2)?

**Comment by joneshf** [comment]
Probably also octal. I like the idea of money style. Is there a generic name for that?

**Comment by Jonplussed** [comment]
@joneshf Not for all currency, because the precision ranges from 0 to 3 across countries. But I'll search for the more-limited case.

**Comment by Jonplussed** [comment]
Looks like currency is all over the place, so I'll just leave it with the common conversions found in other languages. Added the ones you mentioned in PR #5.
